name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish for win-x86
      run: dotnet publish ./SessionManager.csproj -c Release -r win-x86 --self-contained false -p:PublishSingleFile=true -o ./output/win-x86

    - name: Publish for win-x64
      run: dotnet publish ./SessionManager.csproj -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true -o ./output/win-x64

    - name: Zip win-x86
      run: zip -j win-x86.zip ./output/win-x86/*

    - name: Zip win-x64
      run: zip -j win-x64.zip ./output/win-x64/*

    - name: Extract tag name
      id: extract_tag
      run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref }}
        name: ${{ env.TAG_NAME }}
        body: |
          ## Release Notes
          This release includes the build artifacts for `win-x86` and `win-x64`.
        artifacts: "win-x86.zip,win-x64.zip"
        token: ${{ secrets.GITHUB_TOKEN }}

    # - name: Upload win-x86.zip
    #   uses: actions/upload-artifact@v4.3.3
    #   with:
    #     name: win-x86
    #     path: win-x86.zip

    # - name: Upload win-x64.zip
    #   uses: actions/upload-artifact@v4.3.3
    #   with:
    #     name: win-x64
    #     path: win-x64.zip

#   release:
#     needs: build
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Download win-x86.zip
#         uses: actions/download-artifact@v2
#         with:
#           name: win-x86
#           path: .

#       - name: Download win-x64.zip
#         uses: actions/download-artifact@v2
#         with:
#           name: win-x64
#           path: .

    #   - name: Create GitHub Release
    #     uses: ncipollo/release-action@v1
    #     with:
    #       tag: ${{ github.ref }}
    #       name: Release ${{ github.ref }}
    #       body: |
    #         ## Release Notes
    #         This release includes the build artifacts for `win-x86` and `win-x64`.
    #       artifacts: "win-x86.zip,win-x64.zip"
    #       token: ${{ secrets.GITHUB_TOKEN }}
